### ISSUE TITLE
Void Linux dns_sd.h

### ISSUE THREAD

**Issue by johnny-mac** [debauchee/barrier#46] opened 2018-05-23 14:54 UTC
Sorry I don't know where the template went but this field is completely blank, I saw it for a second but it went away. I'll fill it out if I have to, sorry.

Trying to get Barrier to build on Void Linux (GLIBC) but can't seem to do so, it tells me:

CMake Error at CMakeLists.txt:191 (message):
  Missing header: dns_sd.h

I've installed c-ares c-ares-devel nss-mdns mDNSResponder and any other dependencies I could find... but still get this error.

**Comment by johnny-mac** [comment] 2018-05-23 17:35
configure_args="--disable-qt3 --disable-qt4 --disable-mono --disable-monodoc
 --disable-doxygen-doc --enable-compat-libdns_sd --enable-compat-howl
 --with-xml=expat --with-avahi-user=avahi --with-avahi-group=avahi
 --with-avahi-priv-access-group=network --with-autoipd-user=avahi
 --with-autoipd-group=avahi --with-distro=none --disable-xmltoman
 --disable-static ssp_cv_lib=no --enable-python --disable-pygtk
 --disable-glib --disable-python-dbus --disable-gobject --disable-gtk
 --disable-gtk3 --disable-dbm --disable-introspection --sbindir=/usr/bin
 --disable-pygobject"

dns_sd is enabled, why isn't it working? I even custom-compiled AVAHI through the Void Linux template yet I still get this funny error...

**Comment by Johnnynator** [comment] 2018-05-25 14:30
The problem is that VoidLinux does provide `dns_sd.h` like FreeBSD in the `avahi-compat-libdns_sd` subdirectory. Adding `/usr/include/avahi-compat-libdns_sd` to the `include_directories` should help.

**Comment by Johnnynator** [comment] 2018-05-25 17:31
I created a template for Void. https://github.com/Johnnynator/void-packages/commit/281c380a5ad88e1e035878c6045ee815c7c409ec
Will have to fix some stuff first before it will be in the void repo.

**Comment by johnny-mac** [comment] 2018-05-30 14:00
WOW! Where did you come from Johnnynator? From heaven?! lol 
thank you, this template will make everything much easier. Any idea how long it'll take before it reaches XBPS package manager? I'll probably just build it from template but I'm curious

**Comment by Johnnynator** [comment] 2018-05-30 14:41
It is afaik already in the repo and you can install it with `xbps-install barrier` or `xbps-install barrier-gui`

**Comment by walker0643** [comment] 2018-06-30 17:55
Looks resolved to me. Reopen if not.

**Closed by walker0643** 2018-06-30 17:55 UTC
