### ISSUE TITLE
QT_5.10 not found

### ISSUE THREAD

**Issue by vinaysb** [debauchee/barrier#73] opened 2018-06-27 13:48 UTC
Hello, I tried to install barrier on ubuntu, version 2.10, and copied the bin files to my local bin directory. When i try to open barrier it says,
`barrier: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version "Qt_5.10" not found (required by barrier)`

I installed qt5 but it still gives same error, please help

**Comment by p12tic** [comment] 2018-06-27 13:49
Which version of Qt have you installed?

**Comment by vinaysb** [comment] 2018-06-27 14:01
I installed qt5-default

**Comment by p12tic** [comment] 2018-06-27 14:02
Do `apt search qt5-default`

**Comment by vinaysb** [comment] 2018-06-27 14:03
This is what i got,
```
apt search qt5-default
Sorting... Done
Full Text Search... Done
qt5-default/bionic,now 5.9.5+dfsg-0ubuntu1 amd64 [installed]
  Qt 5 development defaults package
```

**Comment by p12tic** [comment] 2018-06-27 14:05
It looks like the official barrier is compiled against too new Qt.

**Comment by vinaysb** [comment] 2018-06-27 14:06
so what should i do :/

**Comment by p12tic** [comment] 2018-06-27 14:07
Nothing :-) You can either compile your own version, but if you're not a programmer I don't advice to do that. The best course of action is just wait.

**Comment by vinaysb** [comment] 2018-06-27 14:08
damn, it worked on my windows :(  anyway, thanks :+1:

**Comment by walker0643** [comment] 2018-06-30 16:05
Distro repository packages are coming. It's been a hard time getting them going, but once they're up it will just be a matter of finding consistent package maintainers.

Closing because this is not a bug.

**Closed by walker0643** 2018-06-30 16:05 UTC

**Comment by goranGG** [comment] 2018-08-31 15:10
@thewhiteh4t can you link us how to do that?

**Comment by BC30138** [comment] 2019-03-12 13:03
> @thewhiteh4t can you link us how to do that?

First of all - install qt5.10.0 (google), then go https://github.com/debauchee/barrier/wiki/Building-on-Linux. Do steps from page - enjoy.

**Comment by AdrianKoshka** [comment] 2019-03-12 20:26
You really should be using QT5.12 probably.

**Comment by BC30138** [comment] 2019-03-12 20:35
> You really should be using the distros provided version of QT BTW. I don't think we use 5.10 anymore.

Yes, of course. I used old version, because actually don't know anything about qt development and the error informs you that qt version 5.10 exactly is required.

Thank you!
