### ISSUE TITLE
What is the process name? 

### ISSUE THREAD

**Issue by G3TG0T** [debauchee/barrier#1140] opened 2021-04-21 21:34 UTC
This may be a dumb question, so please ignore my ignorance. 

What is the name of the process running for Barrier? 

I'm trying to run some hotkeys from my Elgato stream deck and I can make it program specific. It allows me to hit hotkeys while a program is running, and execute commands. I'm trying to do something like this: "When Barrier.exe is the active window, then run these commands". 

Is this even possible? Is there something in windows that says "barrier is the active window now" ? 

Thanks for the help!

**Comment by p12tic** [comment] 2021-06-25 14:13
Unfortunately I don't think this is possible. There's no "window" for Barrier, it interacts with the windowing system using other, lower level methods.

I'm closing the issue so that I don't need to remember to return back to this again in few weeks. If you still have questions, just post here and I'll come back to answer even though the issue is closed.

**Closed by p12tic** 2021-06-25 14:13 UTC

**Comment by G3TG0T** [comment] 2021-06-25 14:32
> Unfortunately I don't think this is possible. There's no "window" for Barrier, it interacts with the windowing system using other, lower level methods.
> 
> I'm closing the issue so that I don't need to remember to return back to this again in few weeks. If you still have questions, just post here and I'll come back to answer even though the issue is closed.

I assumed that was the case! Thank for the reply! Please have a great weekend!
