### ISSUE TITLE
[Feature request] Login with barrier on client computer

### ISSUE THREAD

**Issue by informathemusic** [debauchee/barrier#730] opened 2020-06-03 09:12 UTC
### Operating Systems ###

Server: Debian buster

Client: Debian buster

### Barrier Version ###

Idk I just apt-ed it

### Feature request ###

Introduce some way to login on the client computer(s)

**Comment by shymega** [comment] 2020-06-03 12:49
Please tell us the version in future - that would really help.. and also, the template should be used; its there for a reason Run `barrierc --version` to get the version.

Duplicate of #508, #540, and #297. Closing.

**Closed by shymega** 2020-06-03 12:49 UTC
