### ISSUE TITLE
Issue with OSX 3 tap finger to look up

### ISSUE THREAD

**Issue by microSoftware** [debauchee/barrier#569] opened 2020-02-17 14:29 UTC
### Operating Systems ###

Client: OSX 10.14.6

### Barrier Version ###
2.3.2
2.1.0
I tried both and it doesn't work.

### Steps to reproduce bug ###
Macbook 1: Enable the 3 finger tap for look up in the Preference > Trackpad option > Lookup and data detector
Macbook 2: Try the 2 finger zoom pinch, 3 fingers pinch. Normally it doesn't work. Any kind of gesture with 2-3-4 fingers doesn't work on the client macbook.

### Other info ###
On the server it works fine.
It's on the client that it doesn't work. It's like Barrier Server is not passing the event data to the client.

**Comment by astavs** [comment] 2021-02-01 00:37
This is a duplicate of issue #591

**Comment by p12tic** [comment] 2021-06-21 18:34
Thanks, closing as duplicate of #591.

**Closed by p12tic** 2021-06-21 18:34 UTC
Labels: enhancement, macOS, no-issue-activity
