### ISSUE TITLE
Linux client pauses

### ISSUE THREAD

**Issue by BtheDestroyer** [debauchee/barrier#58] opened 2018-06-10 02:32 UTC
### Operating Systems ###

Server: Windows 10 build 1803

Client: Linux Mint 18.3 Cinnamon

### Barrier Version ###

2.1.0-RELEASE

### Steps to reproduce bug ###

1. Run the server on Windows
2. Connect with a client on Linux
3. Moving the mouse from Windows to Linux works, but if the mouse stops moving, it won't move for a few seconds when on the client. The same occurs with the keyboard (there's a noticeable delay when beginning to type)

This does not occur when Linux is hosting the server and Windows connects as the client.

**Comment by walker0643** [comment] 2018-09-08 22:35
I have a Win10/arch setup here but I can't reproduce your issue. Can you provide anything that might help me bring out the bug? Can anyone else confirm similar behavior?

**Comment by AngelJA** [comment] 2018-12-09 22:11
I know this is late, but I just had a similar issue, except instead of pausing for a few seconds it was only like a half second.  If I moved the mouse continuously it seemed fine, but if I paused, then the first time I moved the mouse or typed there'd be a noticeable, annoying lag. (Also Windows server, Linux Client)

For me it turned out to be because my Linux Client was on wifi; using ethernet gave me super smooth performance.  So for anyone else having issues I'd consider looking at your network setup.

**Comment by AngelJA** [comment] 2018-12-09 22:34
Followup to my last post:  I did a bit more research and found that the reason ethernet was so much better was because wifi powersave was on.  I won't list the steps to fix that since it may vary, but you should be able to google it. :)

**Comment by AdrianKoshka** [comment] 2018-12-12 23:14
Can this issue be closed?

**Comment by p12tic** [comment] 2018-12-13 18:34
I think barrier could issue a warning when excessive network latency is present. At least users would know that it's something on their side instead of thinking that the software is crap.

**Comment by mirh** [comment] 2019-09-14 19:37
> At least users would know that it's something on their side instead of thinking that the software is crap.

This, a hundred times. 

Though, couldn't barrier also took care of handling powersave? It would be much more user-friendly, and it could even allow still some nice power saving (e.g. if the mouse is on the host, no need to keep it disabled)
I know `wifi.powersave` should be an actual hook for [snaps](https://ubuntu.com/core/docs/networkmanager/snap-configuration/wifi-powersave) then..
but NM can only set [them](https://bugzilla.gnome.org/show_bug.cgi?id=739084) via cfgs, and the kernel dropped [long ago](https://patchwork.kernel.org/patch/7396631/) the api specifically crafted for that..
So, I think the only option would be calling iw? With some [caveats](https://www.ctrl.blog/entry/linux-wifi-dpm-latency.html).

**Comment by xekon** [comment] 2020-04-06 17:19
In my Case I am running Windows 8.1 in QEMU KVM with GPU passthrough for gaming, its the only thing the windows VM gets used for.

Windows 8.1 is the Server and Linux is the client. My linux client occasionally hangs/pauses for what seems to be about 5 seconds. This only happens occasionally.

I would not think latency could be the issue when it happens on the same machine between the VM and Host, any way for me to debug what might be causing this? It often occurs I have the input moved over to the linux client and I am opening a right click menu of the mouse, but thats not the only time, its just one of the times I seem to notice it happen the most. During this time I can move the secondary mouse around that is connected directly to Linux, its just Barrier that appears to be locked up.

**Comment by axtux** [comment] 2020-05-19 16:41
May be related to #617

**Comment by xekon** [comment] 2020-05-19 17:31
I ended up opening my own issue: https://github.com/debauchee/barrier/issues/645

I had issues with barrier the entire time I was using it which was under ubuntu 18.04.
Once I did a clean install of Ubuntu 20.04 and a clean install of my windows 8.1 vm, the issue was magically gone so I closed the issue I had open.

**Comment by p12tic** [comment] 2021-01-10 21:18
This has been fixed in #679.

**Closed by p12tic** 2021-01-10 21:18 UTC
Labels: enhancement
